/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()
const AuthReimbReimbTableLazyImport = createFileRoute(
  '/_auth/reimb/reimb-table',
)()
const AuthReimbAddTicketLazyImport = createFileRoute(
  '/_auth/reimb/add-ticket',
)()
const AuthAuthRegisterLazyImport = createFileRoute('/_auth/auth/register')()
const AuthAuthCheckpointLazyImport = createFileRoute('/_auth/auth/checkpoint')()
const AuthAdminPendingLazyImport = createFileRoute('/_auth/admin/pending')()
const AuthAdminAllUsersLazyImport = createFileRoute('/_auth/admin/all-users')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const AuthReimbReimbTableLazyRoute = AuthReimbReimbTableLazyImport.update({
  id: '/_auth/reimb/reimb-table',
  path: '/reimb/reimb-table',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/reimb/reimb-table.lazy').then((d) => d.Route),
)

const AuthReimbAddTicketLazyRoute = AuthReimbAddTicketLazyImport.update({
  id: '/_auth/reimb/add-ticket',
  path: '/reimb/add-ticket',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/reimb/add-ticket.lazy').then((d) => d.Route),
)

const AuthAuthRegisterLazyRoute = AuthAuthRegisterLazyImport.update({
  id: '/_auth/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/auth/register.lazy').then((d) => d.Route),
)

const AuthAuthCheckpointLazyRoute = AuthAuthCheckpointLazyImport.update({
  id: '/_auth/auth/checkpoint',
  path: '/auth/checkpoint',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/auth/checkpoint.lazy').then((d) => d.Route),
)

const AuthAdminPendingLazyRoute = AuthAdminPendingLazyImport.update({
  id: '/_auth/admin/pending',
  path: '/admin/pending',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/admin/pending.lazy').then((d) => d.Route),
)

const AuthAdminAllUsersLazyRoute = AuthAdminAllUsersLazyImport.update({
  id: '/_auth/admin/all-users',
  path: '/admin/all-users',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/_auth/admin/all-users.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/admin/all-users': {
      id: '/_auth/admin/all-users'
      path: '/admin/all-users'
      fullPath: '/admin/all-users'
      preLoaderRoute: typeof AuthAdminAllUsersLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/admin/pending': {
      id: '/_auth/admin/pending'
      path: '/admin/pending'
      fullPath: '/admin/pending'
      preLoaderRoute: typeof AuthAdminPendingLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/checkpoint': {
      id: '/_auth/auth/checkpoint'
      path: '/auth/checkpoint'
      fullPath: '/auth/checkpoint'
      preLoaderRoute: typeof AuthAuthCheckpointLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auth/register': {
      id: '/_auth/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthAuthRegisterLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reimb/add-ticket': {
      id: '/_auth/reimb/add-ticket'
      path: '/reimb/add-ticket'
      fullPath: '/reimb/add-ticket'
      preLoaderRoute: typeof AuthReimbAddTicketLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/reimb/reimb-table': {
      id: '/_auth/reimb/reimb-table'
      path: '/reimb/reimb-table'
      fullPath: '/reimb/reimb-table'
      preLoaderRoute: typeof AuthReimbReimbTableLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/admin/all-users': typeof AuthAdminAllUsersLazyRoute
  '/admin/pending': typeof AuthAdminPendingLazyRoute
  '/auth/checkpoint': typeof AuthAuthCheckpointLazyRoute
  '/auth/register': typeof AuthAuthRegisterLazyRoute
  '/reimb/add-ticket': typeof AuthReimbAddTicketLazyRoute
  '/reimb/reimb-table': typeof AuthReimbReimbTableLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/admin/all-users': typeof AuthAdminAllUsersLazyRoute
  '/admin/pending': typeof AuthAdminPendingLazyRoute
  '/auth/checkpoint': typeof AuthAuthCheckpointLazyRoute
  '/auth/register': typeof AuthAuthRegisterLazyRoute
  '/reimb/add-ticket': typeof AuthReimbAddTicketLazyRoute
  '/reimb/reimb-table': typeof AuthReimbReimbTableLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/_auth/admin/all-users': typeof AuthAdminAllUsersLazyRoute
  '/_auth/admin/pending': typeof AuthAdminPendingLazyRoute
  '/_auth/auth/checkpoint': typeof AuthAuthCheckpointLazyRoute
  '/_auth/auth/register': typeof AuthAuthRegisterLazyRoute
  '/_auth/reimb/add-ticket': typeof AuthReimbAddTicketLazyRoute
  '/_auth/reimb/reimb-table': typeof AuthReimbReimbTableLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/all-users'
    | '/admin/pending'
    | '/auth/checkpoint'
    | '/auth/register'
    | '/reimb/add-ticket'
    | '/reimb/reimb-table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/all-users'
    | '/admin/pending'
    | '/auth/checkpoint'
    | '/auth/register'
    | '/reimb/add-ticket'
    | '/reimb/reimb-table'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/_auth/admin/all-users'
    | '/_auth/admin/pending'
    | '/_auth/auth/checkpoint'
    | '/_auth/auth/register'
    | '/_auth/reimb/add-ticket'
    | '/_auth/reimb/reimb-table'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  AuthAdminAllUsersLazyRoute: typeof AuthAdminAllUsersLazyRoute
  AuthAdminPendingLazyRoute: typeof AuthAdminPendingLazyRoute
  AuthAuthCheckpointLazyRoute: typeof AuthAuthCheckpointLazyRoute
  AuthAuthRegisterLazyRoute: typeof AuthAuthRegisterLazyRoute
  AuthReimbAddTicketLazyRoute: typeof AuthReimbAddTicketLazyRoute
  AuthReimbReimbTableLazyRoute: typeof AuthReimbReimbTableLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  AuthAdminAllUsersLazyRoute: AuthAdminAllUsersLazyRoute,
  AuthAdminPendingLazyRoute: AuthAdminPendingLazyRoute,
  AuthAuthCheckpointLazyRoute: AuthAuthCheckpointLazyRoute,
  AuthAuthRegisterLazyRoute: AuthAuthRegisterLazyRoute,
  AuthReimbAddTicketLazyRoute: AuthReimbAddTicketLazyRoute,
  AuthReimbReimbTableLazyRoute: AuthReimbReimbTableLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/_auth/admin/all-users",
        "/_auth/admin/pending",
        "/_auth/auth/checkpoint",
        "/_auth/auth/register",
        "/_auth/reimb/add-ticket",
        "/_auth/reimb/reimb-table"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/_auth/admin/all-users": {
      "filePath": "_auth/admin/all-users.lazy.tsx"
    },
    "/_auth/admin/pending": {
      "filePath": "_auth/admin/pending.lazy.tsx"
    },
    "/_auth/auth/checkpoint": {
      "filePath": "_auth/auth/checkpoint.lazy.tsx"
    },
    "/_auth/auth/register": {
      "filePath": "_auth/auth/register.lazy.tsx"
    },
    "/_auth/reimb/add-ticket": {
      "filePath": "_auth/reimb/add-ticket.lazy.tsx"
    },
    "/_auth/reimb/reimb-table": {
      "filePath": "_auth/reimb/reimb-table.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
